services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    environment:
      - CORS_ORIGINS=http://localhost,http://frontend,http://localhost:80,http://frontend:80,http://localhost:5173,http://frontend:5173
      - PORT=3001
      - HOST=0.0.0.0
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:3001