services:
  backend:
    image: balance-backend:latest
    ports:
      - "3001:3001"
    environment:
      - CORS_ORIGINS=http://localhost,http://frontend,http://localhost:80,http://frontend:80,http://localhost:5173,http://frontend:5173
      - PORT=3001
      - HOST=0.0.0.0
    volumes:
      - ./data:/data

  frontend:
    image: balance-frontend:latest
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:3001